language: node_js
node_js:
  - "6"
  - "7"
matrix:
  fast_finish: true
before_install:
  - npm i npm@^4 -g
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run ci
after_success:
  - npm run github-deploy
cache:
  directories:
    - node_modules
